name: napari-raman
channels:
  - conda-forge
dependencies:
  - black
  - colorcet
  - imagecodecs
  - imageio
  - napari
  - numpy
  - pyqtgraph
  - pyside2
  - python
  - qtpy
  - tifffile
  - xarray
  - pip
  - pip:
    - git+git://github.com/biomicrodev/common.git#egg=bmd_common
